#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Sep 02 22:55:25 EDT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=iterationT 3.2.0.zip
