name = "Tylers Mods"
author = "brandon.pgreene"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3b120e8bb4fb89768f8fa712c9b7c192499268bf81652b1f483a55e16008ab6f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
