name = "Tylers Mods"
author = "brandon.pgreene"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d83ddc0fe557bf2af330b850aad3fc7de898f3138281d1d5dfb00d4508112086"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
