name = "Tylers Mods"
author = "brandon.pgreene"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a0f2923dfffd0c4786f5e99236f2eabc575aed437e1b42a8cf6a6eb5a2b77087"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
