name = "Tylers Mods Plus"
author = "brandon.pgreene"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3629b013d93933191e2b0bdd08487136248348e4404d511cae4ca8e61e31bcc"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
