name = "Tylers Mods Plus"
author = "brandon.pgreene"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcc4cf45407905245d7abf88fe4e72abe26a4bc6a551eed0cf45818ab379eb6a"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
