name = "Tylers Mods Plus"
author = "brandon.pgreene"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6cd0bea5745a9b98e0b42ba57f4aa67455fbe3421680af17b550fe3e132393ca"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
