name = "Tylers Mods (mods only)"
author = "brandon.pgreene"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65aea51899ddb4ee854eb791adb760716e69a7b78cdb32f11c1cd9f7c881f176"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
