name = "Tylers Mods (mods only)"
author = "brandon.pgreene"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5d3422f566606e2844f56620b1f84ed116ea8219460e48bbc9461bd2bc2459e8"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
